spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_dev_prod
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    database: mysql
    show-sql: false